import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {StudentProvider} from '@/components/hook/data'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Smart MarkSheet",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StudentProvider>

        {children}
        </StudentProvider>
        </body>
    </html>
  );
}
