import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { StudentProvider, useStudentContext } from "@/components/hook/data";
import { GeminiProvider } from "@/components/hook/api";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Smart MarkSheet",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
 
  return (
    <html lang="en">
      <body className={inter.className}>
        <StudentProvider>
          <GeminiProvider>{children}</GeminiProvider>
        </StudentProvider>
      </body>
    </html>
  );
}
